Repository ALCOpenSource/Mentor-Management-System-Team-6, pull requests merged in 2023-04, with the labels that each got.

#50 Frontend-Docker-Setup -Self-Spirint-1
  frontend/mms-Admin/Dockerfile
  frontend/mms-Admin/src/.dockerignore
  frontend/mms-Admin/vite.config.js
Labels: Self-Sprint 1

#60 Backend project setup
  .gitignore
  README.md
  backend/__init__.py
  backend/mms_app_backend/__init__.py
  backend/mms_app_backend/main.py
  backend/mms_app_backend/mms_app_backend/__init__.py
  backend/mms_app_backend/mms_app_backend/api/__init__.py
  backend/mms_app_backend/mms_app_backend/api/authentication/__init__.py
  backend/mms_app_backend/mms_app_backend/api/authentication/crud.py
  backend/mms_app_backend/mms_app_backend/api/authentication/models.py
  backend/mms_app_backend/mms_app_backend/api/authentication/route.py
  backend/mms_app_backend/mms_app_backend/api/authentication/schemas.py
  backend/mms_app_backend/mms_app_backend/api/authentication/sql_app.db
  backend/mms_app_backend/mms_app_backend/api/authentication/test_authentication.py
  backend/mms_app_backend/mms_app_backend/api/authentication/user_api.py
  backend/mms_app_backend/mms_app_backend/api/utils.py
  backend/mms_app_backend/mms_app_backend/configs/__init__.py
  backend/mms_app_backend/mms_app_backend/configs/database_config.py
  backend/mms_app_backend/sql_app.db
  backend/mms_app_backend/tests/__init__.py
  backend/requirements.txt
Labels: Self-Sprint 1

#57 Forgot/set new password admin app sprint 1 #3
  frontend/mms-Admin/package-lock.json
  frontend/mms-Admin/package.json
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/assets/google-icon.svg
  frontend/mms-Admin/src/assets/images.jsx
  frontend/mms-Admin/src/assets/logo.svg
  frontend/mms-Admin/src/assets/password-reset-sucess-illustration.png
  frontend/mms-Admin/src/components/FormikForm/FormikForm.jsx
  frontend/mms-Admin/src/components/InputField.jsx
  frontend/mms-Admin/src/components/Modals/Modal.jsx
  frontend/mms-Admin/src/components/Modals/PasswordResetModal.jsx
  frontend/mms-Admin/src/components/utilities/Buttons/Button.jsx
  frontend/mms-Admin/src/components/utilities/Buttons/GoogleAuthButton.jsx
  frontend/mms-Admin/src/pages/Auth/AuthHome.jsx
  frontend/mms-Admin/src/pages/Auth/ForgotPassword.jsx
  frontend/mms-Admin/src/pages/Auth/LoginPage.jsx
  frontend/mms-Admin/src/pages/Auth/SetNewPassword.jsx
  frontend/mms-Admin/src/redux/features/NewPasswordSuccess/modalSlice.jsx
  frontend/mms-Admin/src/redux/features/test/IncreaseReduceSlice.jsx
  frontend/mms-Admin/src/redux/features/test/testSlice.jsx
  frontend/mms-Admin/src/redux/store.jsx
  frontend/mms-Admin/tailwind.config.cjs
Labels: Self-Sprint 1

#66 Frontend -Admin-Dashboard-Setup - Self-Sprint-1
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/assets/arrow-down.svg
  frontend/mms-Admin/src/assets/avatar.svg
  frontend/mms-Admin/src/assets/calender.svg
  frontend/mms-Admin/src/assets/gads-elipse.png
  frontend/mms-Admin/src/assets/gads-report.png
  frontend/mms-Admin/src/assets/images.jsx
  frontend/mms-Admin/src/assets/search-icon.png
  frontend/mms-Admin/src/components/Dashboard/DashboardCards/GadsCard.jsx
  frontend/mms-Admin/src/components/Dashboard/DashboardCards/GadsReportCard.jsx
  frontend/mms-Admin/src/components/Dashboard/DashboardCards/TasksCards.jsx
  frontend/mms-Admin/src/components/Dashboard/Navbar.jsx
  frontend/mms-Admin/src/components/Dashboard/Sidebar.jsx
  frontend/mms-Admin/src/components/utilities/ProgressBar/LineProgressBar.jsx
  frontend/mms-Admin/src/pages/Dashboard/Dashboard.jsx
  frontend/mms-Admin/tailwind.config.cjs
Labels: Self-Sprint 1

#67 Backend cicd-setup- Self-Sprint-1
  backend/Dockerfile
  backend/mms_app_backend/main.py
  backend/sql_app.db
  frontend/mms-Admin/.gitignore
Labels: Self-Sprint 1

#71 Feature/backend signup logic self sprint 1#61
  backend/mms_app_backend/main.py
  backend/mms_app_backend/mms_app_backend/api/authentication/constants.py
  backend/mms_app_backend/mms_app_backend/api/authentication/crud.py
  backend/mms_app_backend/mms_app_backend/api/authentication/helpers.py
  backend/mms_app_backend/mms_app_backend/api/authentication/models.py
  backend/mms_app_backend/mms_app_backend/api/authentication/route.py
  backend/mms_app_backend/mms_app_backend/api/authentication/schemas.py
  backend/mms_app_backend/mms_app_backend/api/authentication/test_authentication.py
  backend/mms_app_backend/mms_app_backend/configs/database_config.py
  backend/mms_app_backend/requirements.txt
Labels: Self-Sprint 1

#70 Feature/Profile admin app
  .vscode/settings.json
  frontend/mms-Admin/.eslintrc.cjs
  frontend/mms-Admin/package-lock.json
  frontend/mms-Admin/postcss.config.js
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/assets/profile_assets/calendar.png
  frontend/mms-Admin/src/assets/profile_assets/country.svg
  frontend/mms-Admin/src/assets/profile_assets/email.png
  frontend/mms-Admin/src/assets/profile_assets/github.png
  frontend/mms-Admin/src/assets/profile_assets/globe.png
  frontend/mms-Admin/src/assets/profile_assets/instagram.png
  frontend/mms-Admin/src/assets/profile_assets/linkedin.png
  frontend/mms-Admin/src/assets/profile_assets/location.png
  frontend/mms-Admin/src/assets/profile_assets/twitter.png
  frontend/mms-Admin/src/components/Dashboard/DashboardCards/GadsReportCard.jsx
  frontend/mms-Admin/src/components/Dashboard/Navbar.jsx
  frontend/mms-Admin/src/components/Dashboard/Sidebar.jsx
  frontend/mms-Admin/src/components/FormikForm/FormikForm.jsx
  frontend/mms-Admin/src/components/InputField.jsx
  frontend/mms-Admin/src/pages/Dashboard/DashboardHome.jsx
  frontend/mms-Admin/src/pages/Dashboard/Profile.jsx
Labels: Self-Sprint 1

#74 Frontend - Feature/add login functionality - Self-Sprint-1
  backend/mms_app_backend/mms_app_backend/api/authentication/constants.py
  backend/mms_app_backend/mms_app_backend/api/authentication/helpers.py
  backend/mms_app_backend/mms_app_backend/api/authentication/responses.py
  backend/mms_app_backend/mms_app_backend/api/authentication/route.py
  backend/mms_app_backend/mms_app_backend/api/authentication/schemas.py
  backend/mms_app_backend/mms_app_backend/api/authentication/test_authentication.py
Labels: Self-Sprint 1

#76 Frontend - Admin Settings Setup- Self-Sprint-1
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/components/Dashboard/Settings/Sidebar.jsx
  frontend/mms-Admin/src/pages/Dashboard/DashboardHome.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/SettingsHome.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/Support.jsx
Labels: Self-Sprint 1

#80 Fix/backend login-sign up-merge -Self-Sprint-1
  backend/mms_app_backend/main.py
  backend/mms_app_backend/mms_app_backend/api/authentication/crud.py
  backend/mms_app_backend/mms_app_backend/api/authentication/helpers.py
  backend/mms_app_backend/mms_app_backend/api/authentication/responses.py
  backend/mms_app_backend/mms_app_backend/api/authentication/route.py
  backend/mms_app_backend/mms_app_backend/api/authentication/test_authentication.py
  backend/mms_app_backend/mms_app_backend/configs/database_config.py
  backend/mms_app_backend/requirements.txt
Labels: Self-Sprint 1

#81 Setting-FAQ-Admin-App-Sprint_1
  frontend/mms-Admin/.eslintrc.cjs
  frontend/mms-Admin/package-lock.json
  frontend/mms-Admin/package.json
  frontend/mms-Admin/postcss.config.js
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/components/Dashboard/Navbar.jsx
  frontend/mms-Admin/src/components/Dashboard/Sidebar.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/Faqs/Faqs.css
  frontend/mms-Admin/src/pages/Dashboard/Settings/Faqs/Faqs.jsx
Labels: Sprint 1, Self-Sprint 1

#83 Feature/backend user profile logic self sprint 1#75
  backend/mms_app_backend/main.py
  backend/mms_app_backend/mms_app_backend/api/account_management/__init__.py
  backend/mms_app_backend/mms_app_backend/api/account_management/constants.py
  backend/mms_app_backend/mms_app_backend/api/account_management/crud.py
  backend/mms_app_backend/mms_app_backend/api/account_management/helpers.py
  backend/mms_app_backend/mms_app_backend/api/account_management/models.py
  backend/mms_app_backend/mms_app_backend/api/account_management/responses.py
  backend/mms_app_backend/mms_app_backend/api/account_management/route.py
  backend/mms_app_backend/mms_app_backend/api/account_management/schemas.py
  backend/mms_app_backend/mms_app_backend/api/authentication/constants.py
  backend/mms_app_backend/mms_app_backend/api/authentication/helpers.py
  backend/mms_app_backend/mms_app_backend/api/authentication/models.py
  backend/mms_app_backend/mms_app_backend/api/authentication/responses.py
  backend/mms_app_backend/mms_app_backend/api/authentication/route.py
  backend/mms_app_backend/mms_app_backend/api/authentication/schemas.py
  backend/mms_app_backend/mms_app_backend/api/authentication/test_authentication.py
  backend/mms_app_backend/mms_app_backend/api/models.py
  backend/mms_app_backend/mms_app_backend/api/utils.py
  backend/mms_app_backend/requirements.txt
  backend/sql_app.db
Labels: Self-Sprint 1

#105 Frontend -Admin-Dashboard-Setup - Self-Sprint-1
  frontend/mms-Admin/package-lock.json
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/assets/Hamburger Menu.png
  frontend/mms-Admin/src/assets/images.jsx
  frontend/mms-Admin/src/components/Dashboard/Navbar.jsx
  frontend/mms-Admin/src/components/Dashboard/Sidebar.jsx
  frontend/mms-Admin/src/components/utilities/Buttons/GoogleAuthButton.jsx
  frontend/mms-Admin/src/index.css
  frontend/mms-Admin/src/pages/Auth/ForgotPasswordVerifyEmail.jsx
  frontend/mms-Admin/src/pages/Auth/LoginPage.jsx
  frontend/mms-Admin/src/pages/Dashboard/DashboardHome.jsx
Labels: Self-Sprint 1

#100 Feature/backend task mentors mentor manager admin app sprint2#98
  backend/mms_app_backend/main.py
  backend/mms_app_backend/mms_app_backend/api/account_management/crud.py
  backend/mms_app_backend/mms_app_backend/api/account_management/models.py
  backend/mms_app_backend/mms_app_backend/api/authentication/models.py
  backend/mms_app_backend/mms_app_backend/api/tasks/__init__.py
  backend/mms_app_backend/mms_app_backend/api/tasks/constants.py
  backend/mms_app_backend/mms_app_backend/api/tasks/crud.py
  backend/mms_app_backend/mms_app_backend/api/tasks/models.py
  backend/mms_app_backend/mms_app_backend/api/tasks/responses.py
  backend/mms_app_backend/mms_app_backend/api/tasks/route.py
  backend/mms_app_backend/mms_app_backend/api/tasks/schemas.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/8f60e6cce3c9_alembic_tasks_created.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/fe8ea9fb3a4d_alembic_initial_revision.py
  backend/mms_app_backend/mms_app_backend/configs/mail_server_configs.py
  backend/mms_app_backend/requirements.txt
Labels: Sprint 2, Self-Sprint 2

#106 Backend - Task-Mentors/Mentor Manager-Admin-App - Sprint 2
  backend/mms_app_backend/mms_app_backend/api/tasks/crud.py
  backend/mms_app_backend/mms_app_backend/api/tasks/models.py
  backend/mms_app_backend/mms_app_backend/api/tasks/responses.py
  backend/mms_app_backend/mms_app_backend/api/tasks/route.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/bf806ba2ee7d_added_task_open_or_completed_state.py
Labels: Sprint 2

#107 Mm task admin app sprint 2
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/assets/delete.png
  frontend/mms-Admin/src/assets/images.jsx
  frontend/mms-Admin/src/components/Modals/TasksModal.jsx
  frontend/mms-Admin/src/components/utilities/Toggle.jsx
  frontend/mms-Admin/src/pages/Dashboard/Dashboard.jsx
  frontend/mms-Admin/src/pages/Dashboard/Tasks/Tasks.css
  frontend/mms-Admin/src/pages/Dashboard/Tasks/Tasks.jsx
  frontend/mms-Admin/src/pages/Dashboard/Tasks/task.png
  frontend/mms-Admin/src/pages/Dashboard/Tasks/taskIcon2.png
  frontend/mms-Admin/src/redux/features/tasks/tasksSlice.jsx
  frontend/mms-Admin/src/redux/store.jsx
Labels: Sprint 2
