Repository ALCOpenSource/Mentor-Management-System-Team-6, pull requests merged in 2023-05, with the labels that each got.

#108 Discussion-Forum-Admin-App - Sprint 2
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/assets/3-dots.svg
  frontend/mms-Admin/src/assets/bookmark-icon.svg
  frontend/mms-Admin/src/assets/clock-time-icon.svg
  frontend/mms-Admin/src/assets/comment-icon.svg
  frontend/mms-Admin/src/assets/images.jsx
  frontend/mms-Admin/src/assets/share-icon.svg
  frontend/mms-Admin/src/components/Dashboard/DiscussionForum/DiscussionPost.jsx
  frontend/mms-Admin/src/components/Dashboard/Settings/Socials.jsx
  frontend/mms-Admin/src/components/Dashboard/Sidebar.jsx
  frontend/mms-Admin/src/components/InputField.jsx
  frontend/mms-Admin/src/index.css
  frontend/mms-Admin/src/pages/Dashboard/Dashboard.jsx
  frontend/mms-Admin/src/pages/Dashboard/DiscussionForum/DiscussionForum.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/SettingChangePassword.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/SettingsGeneral.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/SettingsHome.jsx
  frontend/mms-Admin/src/pages/Dashboard/Tasks/Tasks.jsx
  frontend/mms-Admin/src/pages/Dashboard/styles/dashboard.module.css
Labels: Sprint 2

#111 Mm new task admin app sprint2
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/assets/images.jsx
  frontend/mms-Admin/src/assets/new_task.png
  frontend/mms-Admin/src/assets/remove.png
  frontend/mms-Admin/src/components/Modals/NewTaskModal.jsx
  frontend/mms-Admin/src/pages/Dashboard/Dashboard.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/Notifications/Notifications.jsx
  frontend/mms-Admin/src/pages/Dashboard/Tasks/NewTask.jsx
  frontend/mms-Admin/src/pages/Dashboard/Tasks/Tasks.jsx
  frontend/mms-Admin/src/redux/features/tasks/tasksSlice.jsx
Labels: Sprint 2

#116 Settings-Password-Admin-App - Sprint 1
  frontend/mms-Admin/src/components/Dashboard/Sidebar.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/SettingChangePassword.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/SettingsGeneral.jsx
  frontend/mms-Admin/src/redux/features/userSlice.jsx
Labels: Self-Sprint 1

#124 Messages
  frontend/mms-Admin/package-lock.json
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/assets/messages/attachment-clip.svg
  frontend/mms-Admin/src/assets/messages/close.svg
  frontend/mms-Admin/src/assets/messages/dropdown.png
  frontend/mms-Admin/src/assets/messages/emoji-smiley.svg
  frontend/mms-Admin/src/assets/messages/filter.svg
  frontend/mms-Admin/src/assets/messages/message-delivered.svg
  frontend/mms-Admin/src/assets/messages/message-loading.svg
  frontend/mms-Admin/src/assets/messages/message-sent.svg
  frontend/mms-Admin/src/assets/messages/next-message.svg
  frontend/mms-Admin/src/assets/messages/next-page.svg
  frontend/mms-Admin/src/assets/messages/offline.svg
  frontend/mms-Admin/src/assets/messages/prev-message.svg
  frontend/mms-Admin/src/assets/messages/prev-page.svg
  frontend/mms-Admin/src/assets/messages/search.svg
  frontend/mms-Admin/src/pages/Dashboard/Messages/BroadcastMessage.jsx
  frontend/mms-Admin/src/pages/Dashboard/Messages/BrowsePeople.jsx
  frontend/mms-Admin/src/pages/Dashboard/Messages/Chats.jsx
  frontend/mms-Admin/src/pages/Dashboard/Messages/MessageHome.jsx
  frontend/mms-Admin/src/pages/Dashboard/Messages/NoMessage.jsx
  frontend/mms-Admin/src/pages/Dashboard/Profile.jsx
Labels: Self-Sprint 2

#126 Feature/Settings-Password-Admin-App - Sprint 1
  frontend/mms-Admin/src/components/Dashboard/Settings/ProfilePictureUpload.jsx
  frontend/mms-Admin/src/components/Dashboard/Settings/Socials.jsx
  frontend/mms-Admin/src/components/InputField.jsx
  frontend/mms-Admin/src/components/Modals/EditPost.jsx
  frontend/mms-Admin/src/pages/Auth/LoginPage.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/SettingChangePassword.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/SettingsGeneral.jsx
  frontend/mms-Admin/src/redux/features/userSlice.jsx
Labels: Self-Sprint 1

#127 Feature/backend messages admin app sprint 2#93
  backend/mms_app_backend/mms_app_backend/api/messages/constants.py
  backend/mms_app_backend/mms_app_backend/api/messages/crud.py
  backend/mms_app_backend/mms_app_backend/api/messages/models.py
  backend/mms_app_backend/mms_app_backend/api/messages/responses.py
  backend/mms_app_backend/mms_app_backend/api/messages/route.py
  backend/mms_app_backend/mms_app_backend/api/messages/schemas.py
  backend/mms_app_backend/mms_app_backend/api/tasks/route.py
  backend/mms_app_backend/mms_app_backend/api/tasks/schemas.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/0c47db4bbb13_added_is_active_flag_to_message_model.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/1762e26440e7_added_is_default_flag_to_message_model.py
Labels: Self-Sprint 2

#138 Select new task for mentors/mentor manager admin app sprint2
  frontend/mms-Admin/package-lock.json
  frontend/mms-Admin/src/pages/Dashboard/Tasks/NewTask.jsx
Labels: Self-Sprint 2

#141 Feature/admin post
  backend/mms_app_backend/.gitignore
  backend/mms_app_backend/main.py
  backend/mms_app_backend/mms_app_backend/api/account_management/models.py
  backend/mms_app_backend/mms_app_backend/api/mentors/constants.py
  backend/mms_app_backend/mms_app_backend/api/mentors/crud.py
  backend/mms_app_backend/mms_app_backend/api/mentors/responses.py
  backend/mms_app_backend/mms_app_backend/api/mentors/route.py
  backend/mms_app_backend/mms_app_backend/api/mentors/schemas.py
  backend/mms_app_backend/mms_app_backend/api/posts/__init__.py
  backend/mms_app_backend/mms_app_backend/api/posts/constants.py
  backend/mms_app_backend/mms_app_backend/api/posts/crud.py
  backend/mms_app_backend/mms_app_backend/api/posts/models.py
  backend/mms_app_backend/mms_app_backend/api/posts/responses.py
  backend/mms_app_backend/mms_app_backend/api/posts/route.py
  backend/mms_app_backend/mms_app_backend/api/posts/schemas.py
  backend/mms_app_backend/mms_app_backend/api/tasks/crud.py
  backend/mms_app_backend/mms_app_backend/api/tasks/responses.py
  backend/mms_app_backend/mms_app_backend/api/tasks/route.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/fe8ea9fb3a4d_alembic_initial_revision.py
Labels: Self-Sprint 2

#145 Mentor/Mentor Managers Program-Admin-App - Sprint 3
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/components/Dashboard/Mentors/MentorProgramCard.jsx
  frontend/mms-Admin/src/pages/Dashboard/Mentors/MentorsPrograms.jsx
  frontend/mms-Admin/src/pages/Dashboard/Settings/Archive.jsx
Labels: Sprint 3

#155 Integration/tasks and new task
  frontend/mms-Admin/src/components/Dashboard/Tasks/TasksLoading.jsx
  frontend/mms-Admin/src/pages/Dashboard/Tasks/NewTask.jsx
  frontend/mms-Admin/src/pages/Dashboard/Tasks/Tasks.jsx
Labels: Self-Sprint 3

#154 Create new program admin app sprint 4 backend#153
  backend/README.md
  backend/Read.md
  backend/mms_app_backend/main.py
  backend/mms_app_backend/mms_app_backend/api/account_management/crud.py
  backend/mms_app_backend/mms_app_backend/api/account_management/helpers.py
  backend/mms_app_backend/mms_app_backend/api/account_management/models.py
  backend/mms_app_backend/mms_app_backend/api/account_management/route.py
  backend/mms_app_backend/mms_app_backend/api/authentication/crud.py
  backend/mms_app_backend/mms_app_backend/api/authentication/models.py
  backend/mms_app_backend/mms_app_backend/api/authentication/schemas.py
  backend/mms_app_backend/mms_app_backend/api/authentication/test_authentication.py
  backend/mms_app_backend/mms_app_backend/api/mentor_managers/crud.py
  backend/mms_app_backend/mms_app_backend/api/mentor_managers/route.py
  backend/mms_app_backend/mms_app_backend/api/mentor_managers/schemas.py
  backend/mms_app_backend/mms_app_backend/api/mentors/constants.py
  backend/mms_app_backend/mms_app_backend/api/mentors/crud.py
  backend/mms_app_backend/mms_app_backend/api/mentors/responses.py
  backend/mms_app_backend/mms_app_backend/api/mentors/route.py
  backend/mms_app_backend/mms_app_backend/api/mentors/schemas.py
  backend/mms_app_backend/mms_app_backend/api/messages/crud.py
  backend/mms_app_backend/mms_app_backend/api/messages/models.py
  backend/mms_app_backend/mms_app_backend/api/messages/schemas.py
  backend/mms_app_backend/mms_app_backend/api/posts/crud.py
  backend/mms_app_backend/mms_app_backend/api/posts/models.py
  backend/mms_app_backend/mms_app_backend/api/posts/responses.py
  backend/mms_app_backend/mms_app_backend/api/posts/route.py
  backend/mms_app_backend/mms_app_backend/api/posts/schemas.py
  backend/mms_app_backend/mms_app_backend/api/programs/__init__.py
  backend/mms_app_backend/mms_app_backend/api/programs/constants.py
  backend/mms_app_backend/mms_app_backend/api/programs/crud.py
  backend/mms_app_backend/mms_app_backend/api/programs/responses.py
  backend/mms_app_backend/mms_app_backend/api/programs/route.py
  backend/mms_app_backend/mms_app_backend/api/programs/schemas.py
  backend/mms_app_backend/mms_app_backend/api/tasks/constants.py
  backend/mms_app_backend/mms_app_backend/api/tasks/crud.py
  backend/mms_app_backend/mms_app_backend/api/tasks/models.py
  backend/mms_app_backend/mms_app_backend/api/tasks/responses.py
  backend/mms_app_backend/mms_app_backend/api/tasks/route.py
  backend/mms_app_backend/mms_app_backend/api/tasks/schemas.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/env.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/066c0bca01cc_removed_messages_associations.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/0c47db4bbb13_added_is_active_flag_to_message_model.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/104ecf84a40f_created_user_conversation_relationship.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/12313f8d1a75_added_messages_associations.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/1762e26440e7_added_is_default_flag_to_message_model.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/1811c401371b_fixed_typo_messages_associations.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/5f28072965c1_alembic_initial_revision.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/6158b616a6a1_fixed_typo_messages_associations.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/83195a444300_association_tables_not_inheriting_from_.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/8f60e6cce3c9_alembic_tasks_created.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/a58ef99360d3_new_conversations_link.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/b482819d0b10_fixed_typo_messages_associations.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/bbe28d4a49cd_new_conversations_link.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/bf806ba2ee7d_added_task_open_or_completed_state.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/d7cfeeb2de58_association_tables_not_inheriting_from_.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/da7292bbdbf0_added_reset_token_expirations.py
  backend/mms_app_backend/mms_app_backend/configs/alembic_config/versions/f1e83bddb90b_fixed_typo_messages_associations.py
  backend/mms_app_backend/mms_app_backend/configs/database_config.py
  backend/mms_app_backend/mms_app_backend/configs/mail_server_configs.py
Labels: Self-Sprint 4

#169 Edit Program Page-Admin-App - Sprint 4
  frontend/mms-Admin/src/App.jsx
  frontend/mms-Admin/src/assets/images.jsx
  frontend/mms-Admin/src/assets/program-avatar.svg
  frontend/mms-Admin/src/components/Dashboard/Programs/CreateProgramSuccessModal.jsx
  frontend/mms-Admin/src/components/Dashboard/Programs/EditProgramSuccessModal.jsx
  frontend/mms-Admin/src/components/Dashboard/Programs/UploadAvatar.jsx
  frontend/mms-Admin/src/pages/Dashboard/Programs/EditProgram.jsx
  frontend/mms-Admin/src/pages/Dashboard/Programs/NewProgram.jsx
  frontend/mms-Admin/src/pages/Dashboard/Programs/ProgramsHome.jsx
Labels: Sprint 4
